spring:
  application:
    name: sales-web

server:
  port: 8082
  
jsf:
  PROJECT_STAGE: Development
  primefaces:
    theme: bootstrap
    FONT_AWESOME: true

eureka:
  password: eureka
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@localhost:8761/eureka/
  instance:
    #leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
      
  endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
    
logging.level:
  
  # Enable request logging
  org.springframework.web.filter: DEBUG
  
  # Enable logging of access token request
  org.apache.http.headers: DEBUG
  org.springframework.web.client: DEBUG
  
  logging.level.org.springframework.security: DEBUG